module CurrencyConverterHelper
    def currency_list
    [
      { code: "USD", name: "US Dollar", flag: "united-states" },
      { code: "EUR", name: "Euro", flag: "european-union" },
      { code: "GBP", name: "British Pound", flag: "united-kingdom" },
      { code: "JPY", name: "Japanese Yen", flag: "japan" },
      { code: "CAD", name: "Canadian Dollar", flag: "canada" },
      { code: "AUD", name: "Australian Dollar", flag: "australia" },
      { code: "CHF", name: "Swiss Franc", flag: "switzerland" },
      { code: "CNY", name: "Chinese Yuan", flag: "china" },
      { code: "SEK", name: "Swedish Krona", flag: "sweden" },
      { code: "NZD", name: "New Zealand Dollar", flag: "new-zealand" },
      { code: "NOK", name: "Norwegian Krone", flag: "norway" },
      { code: "SGD", name: "Singapore Dollar", flag: "singapore" },
      { code: "HKD", name: "Hong Kong Dollar", flag: "hong-kong" },
      { code: "KRW", name: "South Korean Won", flag: "south-korea" },
      { code: "BRL", name: "Brazilian Real", flag: "brazil" },
      { code: "INR", name: "Indian Rupee", flag: "india" },
      { code: "RUB", name: "Russian Ruble", flag: "russia" },
      { code: "ZAR", name: "South African Rand", flag: "south-africa" },
      { code: "PHP", name: "Philippine Peso", flag: "philippines" },
      { code: "THB", name: "Thai Baht", flag: "thailand" },
      { code: "MYR", name: "Malaysian Ringgit", flag: "malaysia" },
      { code: "IDR", name: "Indonesian Rupiah", flag: "indonesia" },
      { code: "VND", name: "Vietnamese Dong", flag: "vietnam" },
      { code: "MXN", name: "Mexican Peso", flag: "mexico" },
      { code: "TRY", name: "Turkish Lira", flag: "turkey" },
      { code: "ILS", name: "Israeli Shekel", flag: "israel" },
      { code: "SAR", name: "Saudi Riyal", flag: "saudi-arabia" },
      { code: "AED", name: "UAE Dirham", flag: "united-arab-emirates" },
      { code: "EGP", name: "Egyptian Pound", flag: "egypt" },
      { code: "KWD", name: "Kuwaiti Dinar", flag: "kuwait" },
      { code: "QAR", name: "Qatari Riyal", flag: "qatar" },
      { code: "BHD", name: "Bahraini Dinar", flag: "bahrain" },
      { code: "OMR", name: "Omani Rial", flag: "oman" },
      { code: "JOD", name: "Jordanian Dinar", flag: "jordan" },
      { code: "LBP", name: "Lebanese Pound", flag: "lebanon" },
      { code: "PKR", name: "Pakistani Rupee", flag: "pakistan" },
      { code: "BDT", name: "Bangladeshi Taka", flag: "bangladesh" },
      { code: "LKR", name: "Sri Lankan Rupee", flag: "sri-lanka" },
      { code: "NPR", name: "Nepalese Rupee", flag: "nepal" }
    ]
  end
end
